trigger:
  branches:
    include:
    - repo-restructure
    - master
  paths:
    exclude:
    - stream-provider
    - stream-consumer

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build . -f components/shared/Dockerfile 
