trigger:
  branches:
    include:
    - repo-restructure
  paths:
    exclude:
    - stream-provider
    - stream-consumer

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build . -f packages/shared/Dockerfile 
- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'bengreenier - dockerhub'
    repository: 'bengreenier/browserd'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest
