trigger:
  branches:
    include:
    - repo-restructure
  paths:
    exclude:
    - shared/azure-pipelines.yaml
    include: 
    - shared/src

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -f stream-provider/Dockerfile -t bengreenier/browserd/stream-provider:$(Build.BuildId) -t bengreenier/browserd/stream-provider:latest
- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'bengreenier - dockerhub'
    repository: 'bengreenier/browserd'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest
